language: generic

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx


before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create --name csaopt-travisci
  - source activate csaopt-travisci
  # not yet needed: - python setup.py install

script: py.test --cov=csaopt -v tests

after_success:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
          coveralls;
      fi
