name: csaopt
channels:
  - conda-forge
dependencies:
  - python=3.6.4
  - pip
  - pip:
      - msgpack==0.5.6
      - click==7.0
      - numpy==1.16.4
      - msgpack-numpy==0.4.4.1
      - sortedcontainers==2.0.4
      - dramatiq[redis]==1.3.0
      - boto3==1.9.161
      - async-timeout==3.0.0
      - apscheduler==3.5.3
      - sty==1.0.0b7
      - pyhocon==0.3.44
      - mypy==0.620
      - better-exceptions==0.2.2
