name: csaopt
channels:
  - conda-forge
dependencies:
  - python=3.6.4
  - msgpack-python
  - arrow
  - click
  - requests
  - ujson
  - pytest
  - pytest-cov
  - Sphinx
  - coverage
  - coveralls
  - bumpversion
  - flake8=3.4.1
  - pytest-timeout
  - pytest-mock
  - pytest-asyncio
  - pip:
    - numpy
    - msgpack-numpy
    - sortedcontainers
    - dramatiq[redis, watch]
    - boto3==1.7.84
    - moto
    - async-timeout
    - apscheduler
    - coloredlogs
    - sty
    - pyhocon
    - mypy
    - sphinxcontrib-napoleon
    - yapf
