name: csaopt
channels:
  - conda-forge
dependencies:
  - python=3.6
  - boto3
  - msgpack-python
  - arrow
  - click
  - requests
  - ujson
  - pytest
  - pytest-cov
  - Sphinx
  - coverage
  - coveralls
  - bumpversion
  - flake8
  - pytest-timeout
  - pytest-mock
  - pip:
    - aiokafka
    - lz4tools
    - xxhash
    - pyhocon
    - mypy
    - sphinxcontrib-napoleon
