name: csaopt
channels:
  - conda-forge
dependencies:
  - python=3.6.4
  - pip
  - pip:
      - msgpack==0.5.6
      - click==7.0
      - numpy==1.16.4
      - msgpack-numpy==0.4.4.1
      - sortedcontainers==2.0.4
      - dramatiq[redis, watch]==1.3.0
      - boto3==1.9.161
      - moto==1.3.8
      - async-timeout==3.0.0
      - apscheduler==3.5.3
      - sty==1.0.0b7
      - pyhocon==0.3.44
      - mypy==0.620
      - pytest==3.8.1
      - pytest-cov==2.6.0
      - pytest-timeout==1.3.2
      - pytest-mock==1.10.0
      - pytest-asyncio==0.9.pytest-asyncio==0.9.00
      - Sphinx==1.8.1
      - coverage==4.5.1
      - coveralls==1.5.1
      - flake8==3.4.1
      - docker==3.5.0
      - yapf==0.24.0
      - better-exceptions==0.2.2
