---
- hosts: msgqueue
  vars:
    zmqpp_version: 4.1.2
    git_repo: https://github.com/d53dave/csaopt-zmq.git
  tasks:
   - name: Add cmake ppa
     apt_repository: repo='ppa:george-edison55/cmake-3.x' update_cache=yes
     sudo: yes

   - name: Install required packages
     apt: pkg={{item}} state=installed
     sudo: yes
     with_items:
      - build-essential
      - git
      - cmake
      - libzmq-dev
      - libcapnp-dev
      - ruby

   - name: Create tmp directory for zmqpp install
     file: path=/tmp/zmqpp-{{zmqpp_version}} state=directory

   - name: Download and unarchive zmqpp #https://github.com/zeromq/zmqpp/releases/tag/4.1.2
     unarchive:
       src: https://github.com/zeromq/zmqpp/archive/{{zmqpp_version}}.tar.gz
       copy: no
       dest: /tmp
       creates: /tmp/zmqpp-{{zmqpp_version}}/CMakeLists.txt

   - name: build zmqpp
     shell: cmake . && make
     args:
       chdir: /tmp/zmqpp-{{zmqpp_version}}
       creates: /tmp/zmqpp-{{zmqpp_version}}/libzmqpp.so

   - name: install zmqpp
     shell: make install
     sudo: yes
     args:
       chdir: /tmp/zmqpp-{{zmqpp_version}}
       creates: /usr/local/lib/libzmqpp.so

   - name: ssh-keyscan the git server
     shell: ssh-keyscan -H -t dsa github.org >> ~/.ssh/known_hosts 2>&1

   - name: clone project from git
     git: repo={{ git_repo }} dest=~/msgqueue version=master accept_hostkey=yes

   - name: build project
     shell: cmake . && make csaopt-tidings csaopt_zmq
     args:
       chdir: ~/msgqueue/
     register: compiled

   - name: install pleaserun ruby gem
     shell: gem install pleaserun --no-ri --no-rdoc
     sudo: yes

   - name: generate service script
     command: pleaserun --install -p sysv -v lsb-3.1 --name msgqueue /home/{{ ansible_ssh_user }}/msgqueue/csaopt_zmq
     sudo: yes
     args:
       creates: /etc/init.d/msgqueue

   - name: Start messagequeue
     service: name=msgqueue state=started
     sudo: yes
